import { County } from './county';

export var COUNTIES: County[] = [
  { id: 1, name: 'Bernalillo', projects: 39 },
  { id: 2, name: 'Catron', projects: 1 },
  { id: 3, name: 'Chaves', projects: 22 },
  { id: 4, name: 'Cibola', projects: 82 },
  { id: 5, name: 'Colfax', projects: 105 },
  { id: 6, name: 'Curry', projects: 33 },
  { id: 7, name: 'De Baca', projects: 84 },
  { id: 8, name: 'Dona Ana', projects: 56 },
  { id: 9, name: 'Eddy', projects: 192 },
  { id: 10, name: 'Grant', projects: 149 },
  { id: 11, name: 'Guadalupe', projects: 174 },
  { id: 12, name: 'Harding', projects: 182 },
  { id: 13, name: 'Hidalgo', projects: 109 },
  { id: 14, name: 'Lea', projects: 16 },
  { id: 15, name: 'Lincoln', projects: 200 },
  { id: 16, name: 'Los Alamos', projects: 127 },
  { id: 17, name: 'Luna', projects: 7 },
  { id: 18, name: 'McKinley', projects: 194 },
  { id: 19, name: 'Mora', projects: 90 },
  { id: 20, name: 'Otero', projects: 61 },
  { id: 21, name: 'Quay', projects: 83 },
  { id: 22, name: 'Rio Arriba', projects: 111 },
  { id: 23, name: 'Roosevelt', projects: 175 },
  { id: 24, name: 'San Juan', projects: 91 },
  { id: 25, name: 'San Miguel', projects: 169 },
  { id: 26, name: 'Sandoval', projects: 166 },
  { id: 27, name: 'Santa Fe', projects: 138 },
  { id: 28, name: 'Sierra', projects: 45 },
  { id: 29, name: 'Socorro', projects: 156 },
  { id: 30, name: 'Taos', projects: 78 },
  { id: 31, name: 'Torrance', projects: 130 },
  { id: 32, name: 'Union', projects: 22 },
  { id: 33, name: 'Valencia', projects: 83 }
];
